### ISSUE TITLE
iOS disapproval

### ISSUE THREAD

**Issue by damerell** [apollovy/crawl-ios#2]
David Damerell here.

You do not have my permission to violate the GPL under any circumstances. This would be true even if you hadn't just emailed 500 people without using the Bcc: field, but I'm certainly enjoying writing this more than I otherwise would.

Furthermore, while my contributions are very minor, some major contributors are long gone (some may even be dead). You will never get the permission you want.

**Comment by damerell** [comment]
Please at least don't exacerbate matters by continuing to email 500 people at once for a discussion you're having with one of them.

**Comment by apollovy** [comment]
Hey, David. I'm not going to violate the GPL, the intent is to somehow make it possible to give iOS users the ability to play the game. As you might know, now they don't have that ability.
Of course, those with the right tools are able to take the sources and build the app themselves, since the source is open, but the majority is not able to do it. I think it's unfair.
About bcc: I really know that the question is not that simple, so I think that the  recipients might themselves decide whether to reply to me directly or to all at once to have a further discussion. And I see they do it.
Am I correct that in case none from the contributors that are listed and were reached is against the publishing, then the GPL cannot be considered violated up until some person not from this list would concern that their rights were violated? If yes, then I think it is at least worth publishing the app an if someone would be against, then i can have another round of negotiations with them, but up until that moment all the iOS players would benefit from playing.
Also, maybe you know better ways of giving iOS players such an ability to pay dcss on their devices? I'd be happy to do it there other way around if it's possible.

**Comment by damerell** [comment]
If you're not going to violate the GPL, you're not going to publish in the Apple App Store, since the two are completely incompatible.

The question of Bcc: is that simple. Don't email 500 people without using it. Don't reply to what one of them wrote without using it. It is never appropriate to have a To: line with that many people in it.

You are not correct that if it's hard to get permission you're allowed to pretend you have it even though you don't, but above and beyond that at least one contributor - me - has explicitly denied you permission (and additionally, Kurt Kartaltepe's reply asking for a 10% tranche of all earnings and that if this is appealing your lawyer should reach out is, unless I'm mistaken, saying no but in a funnier way.)

**Comment by apollovy** [comment]
About Kurt's answer: since the app is meant to be free, I even can promise everyone 100% of earnings, meaning it would still be 0 😀
And yes, I see and value your denial, but possibly you've got my intent wrong. I'm not trying to violate the GPL: instead, we can distribute the app to the App store under a license that will permit it, possibly as close to GPL as possible.
If this doesn't fit you, then I please you to share your vision about how plus-minus the same can be achieved the other way.
Again, I just wanna give people the ability to play. I don't wanna earn money from this or something like that. And I'm all about finding an appropriate way, that way or another.
I just ask you not to take it away from those who would really benefit from this: the players.

**Comment by damerell** [comment]
No, you can't distribute it under another licence. You do not have permission to do so. You can only distribute it under the GPL and you would violate it by using the App Store.

And, to be completely clear, while my contributions are very minor, there are no circumstances under which I will agree to relicence them.

**Comment by apollovy** [comment]
AFAIK to distribute under another license, the contributors can make a decision about dual-licensing. This is what I was initially talking about: to have a permission from you the contributors to distribute the app through the App store under license that will permit it.
> And, to be completely clear, while my contributions are very minor, there are no circumstances under which I will agree to relicence them.

Can you please clarify why don't you want for dcss under iOS to happen no matter what, especially taking into account that your contributions are very minor? Won't it make a lot of people happier?

**Comment by damerell** [comment]
> AFAIK to distribute under another license, the contributors can make a decision about dual-licensing. This is what I was initially talking about

I know. I opened this issue to inform you of my decision (and to point out that there is no realistic possibility of you gaining permission from all the contributors or even a significant proportion of them, and to tell you not to email 500 people without using Bcc:).

> Can you please clarify why don't you want for dcss under iOS to happen no matter what

No. This isn't a negotiation. The answer to your request is "no".

**Comment by perryprog** [comment]
(IANAL blah blah grain of salt. Just a minor copyright nerd.)

From my understanding from what you're trying to do, Yuri, is that you need to get _every single past contributor to agree to license each of their contributions under a modified GPLv2 license_. So not only do you need unanimous agreement from _everyone_ (which is already clearly impossible), you would also need to further ensure that future contributions are made under this license (which would either mean another mass request to any future contributors, or a modification to DCSS's current license).

Additionally: while I doubt there is any legal precedent for this specific circumstance, I strongly doubt that simply attempting to circumvent a refusal to re-license one's previous contributions by, for example, reverting them, is valid either. I think an argument could be made that any subsequent contributions are derivative works* on any previous contributions, and thus are bound by the license of those previous contributions, so you are stonewalled by any denial (under most circumstances, there's some other stuff I'm assuming in this case).

While it's really unfortunate, and I do have to commend you for attempting to bring crawl to even more people, I highly doubt that there's any circumstance where this is really possible to pull off.

\* Essentially you're making a derivative work off of a previous version of the project which is limited to be strictly GPLv2, so you're building on the creative work that may be included in any previous contributions. That's my inkling of how this could potentially be viewed, but I don't have any real evidence to support this idea.

**Comment by damerell** [comment]
> every single past contributor to agree to license each of their contributions under a modified GPLv2 license.

... and at this point the odds are very high that at least one of them is _dead_.

**Comment by apollovy** [comment]
Hey, David. I have an idea how we can make DCSS to iOS using a webview and a regular web DCSS client, and I wanted to ask you a question whether you think this will or won't violate the GPL.
Here I have a diagram of my proposal. All the DCSS code is distributed from an external server and runs in a separate environment (iframe), without any other code (js) contacting it in any way. The Apple App Store only distributes the app that provides some styling (for the html game to behave more like regular game and not like an html page: no text selection, no zooming and a couple of other things) and has 
the link to the server that serves the actual game resources.
This way no GPL code is distributed from the app store, no non-GPL code uses DCSS sources (except maybe the webview the iframe is rendered with, but that's just a Safari tab) and no non-GPL code is being executed from the DCSS code. So it looks good to me.
What do you think?
Thank you in advance 🙂

![cordova-iframe Deployment Diagram](https://github.com/apollovy/crawl-ios/assets/1671727/c3952e46-9da4-4801-99e3-2e9114e3cd8a)

**Comment by damerell** [comment]
Well, I'm no lawyer, but isn't there a huge lump of DCSS in the grey box on the left?

**Comment by apollovy** [comment]
> Well, I'm no lawyer, but isn't there a huge lump of DCSS in the grey box on the left?

Me neither, but I'm trying to avoid violating GPL while still delivering the app to iOS users.

If under that grey box you mean “wrapper js, HTML, CSS, images”, then the answer is no, because having any DCSS code there  would definitely violate GPL, since it's a part of DCSS certainly.

And If under that grey box you mean “DCSS js, HTML, CSS, images”, then the answer to your question depends on the moment we look at it:
- does it present in the app files that is being distributed from the app  store? No.
- does it run inside that app? Well, sort of, because of iframe. But that's the same as running GPL site in non-GPL browser.

**Comment by damerell** [comment]
I mean the grey box on the left. OK, so you are generating all the content there yourself?

I think then the question whether anything distributed via the iOS store can then be considered to be a derivative work of DCSS.

**Comment by apollovy** [comment]
Hey, thank you for the answer. It looks like you're correct and all the approaches I was thinking so far are inapplicable. Thank you, I think I'll do something very different, that will not target DCSS directly, but will be helpful for players wishing to play it on iOS. Thank you for your help!
